"""Shared HTML layout for portal pages."""

from __future__ import annotations

from datetime import datetime, timezone

from .util import safe

NAV_PAGES = [
    ("index", "Home", "index.html"),
    ("catalog", "Catalog", "catalog.html"),
    ("scoreboard", "Quality", "scoreboard.html"),
    ("provider", "Currency", "provider.html"),
    ("resources", "Explorer", "resources.html"),
    ("issues", "Issues", "issues.html"),
    ("activity", "Activity", "activity.html"),
]


def generated_timestamp() -> str:
    """Return the UTC generation timestamp for display."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _nav_link(slug: str, label: str, href: str, active_page: str) -> str:
    cls = "nav-link active" if slug == active_page else "nav-link"
    current = ' aria-current="page"' if slug == active_page else ""
    return f'<a href="{href}" class="{cls}"{current}>{safe(label)}</a>'


def nav(active_page: str) -> str:
    """Render the portal navigation."""
    links = "".join(_nav_link(*page, active_page=active_page) for page in NAV_PAGES)
    mobile_links = "".join(
        f'<a href="{href}">{safe(label)}</a>' for _, label, href in NAV_PAGES
    )
    return f"""
<nav class="site-nav" role="navigation" aria-label="Main navigation">
  <a href="index.html" class="nav-logo">AVM Intelligence</a>
  <div class="nav-links">{links}</div>
  <details class="mobile-menu">
    <summary aria-label="Menu">Menu</summary>
    <div class="mobile-nav-links">{mobile_links}</div>
  </details>
  <div class="nav-search" id="search"></div>
</nav>
"""


def pagefind_assets() -> str:
    """Render optional Pagefind assets with graceful no-op if unavailable."""
    return """
  <link href="pagefind/pagefind-ui.css" rel="stylesheet">
  <script src="pagefind/pagefind-ui.js" defer></script>
  <script>
    window.addEventListener("DOMContentLoaded", () => {
      const target = document.querySelector("#search");
      if (!target || !window.PagefindUI) {
        return;
      }
      target.textContent = "";
      new PagefindUI({ element: "#search", showSubResults: true });
    });
  </script>
"""


def shell(
    title: str,
    body_html: str,
    *,
    active_page: str = "",
    extra_head: str = "",
    extra_body_end: str = "",
    generated_at: str = "",
    include_pagefind: bool = True,
) -> str:
    """Wrap page content in a complete HTML document."""
    timestamp = generated_at or generated_timestamp()
    pagefind = pagefind_assets() if include_pagefind else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="AVM Intelligence Portal for Azure Verified Modules metadata.">
  <meta property="og:title" content="{safe(title)}">
  <meta property="og:description" content="Catalog health, quality, provider currency, issues, and activity for AVM modules.">
  <title>{safe(title)}</title>
  <link rel="stylesheet" href="assets/style.css">
{pagefind}{extra_head}
</head>
<body>
{nav(active_page)}
  <main class="page" data-pagefind-body>
    {body_html}
    <footer class="footer">Generated: {safe(timestamp)} · Auto-generated by <code>scripts/generate_site.py</code> · Crayon-HU/avm-metadata</footer>
  </main>
{extra_body_end}
</body>
</html>
"""
