#!/usr/bin/env python3
"""manage_repos.py — Multi-repo git operations across AVM module workspace.

Reads .config/modules.yaml (generated by scripts/generate_config.py) and runs
git operations across all matched repos. Replaces clone_repos.sh/.ps1 and
update_repos.sh/.ps1 while adding fetch, status, branch management, stash,
reset, and arbitrary command pass-through.

Network-bound operations (fetch, update/pull) support parallel execution via
--parallel N to avoid waiting ~200-2000 ms per repo sequentially.

Usage:
    python3 scripts/manage_repos.py clone   [filters] [--full] [--git-name N] [--git-email E]
    python3 scripts/manage_repos.py update  [filters] [--parallel N]
    python3 scripts/manage_repos.py fetch   [filters] [--parallel N]
    python3 scripts/manage_repos.py status  [filters]
    python3 scripts/manage_repos.py branch create <name>    [filters]
    python3 scripts/manage_repos.py branch checkout <name>  [filters] [--fallback]
    python3 scripts/manage_repos.py branch delete <name>    [filters] [--force]
    python3 scripts/manage_repos.py stash   [filters]
    python3 scripts/manage_repos.py stash pop [filters]
    python3 scripts/manage_repos.py reset   [filters] [--hard]
    python3 scripts/manage_repos.py run <cmd...> [-- filters]

Filters (accepted by all subcommands):
    --domain <name>        Filter by catalog domain slug (alias for --domains)
    --type <res|ptn|utl>   Filter by module type (alias for --types)
    --domains <list>       Comma-separated domain slugs (e.g. networking,compute)
    --types <list>         Comma-separated types (res,ptn,utl)
    --module <name>        Filter to a single module by name
    --dry-run              Print actions without executing

    ./avm.sh clone  →  python3 manage_repos.py clone
    ./avm.sh update →  python3 manage_repos.py update
"""

import os
import re
import shutil
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT    = os.path.dirname(SCRIPT_DIR)
MODULES_FILE = os.path.join(REPO_ROOT, ".config", "modules.yaml")
MODULES_DIR  = os.path.join(REPO_ROOT, "data", "modules")

# Default number of days before an analysis block is considered stale
_DEFAULT_STALE_THRESHOLD = 14

ALL_TYPES = ("res", "ptn", "utl")

# ---------------------------------------------------------------------------
# ANSI colours (no external libs)
# ---------------------------------------------------------------------------
_USE_COLOR = sys.stdout.isatty()


def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _USE_COLOR else text


def ok(s: str) -> str:   return _c("32", s)
def warn(s: str) -> str: return _c("33", s)
def err(s: str) -> str:  return _c("31", s)
def dim(s: str) -> str:  return _c("2", s)


# ---------------------------------------------------------------------------
# modules.yaml parser — line-by-line, stdlib only
# ---------------------------------------------------------------------------

def _strip(s: str) -> str:
    return s.strip().strip('"').strip("'")


def load_modules(
    filter_domains: list[str] | None = None,
    filter_types:   list[str] | None = None,
    filter_modules: list[str] | None = None,
) -> list[dict]:
    """
    Parse .config/modules.yaml and return module dicts matching the given filters.

    Each dict has keys: name, domain, type, url, branch.
    filter_domains / filter_types / filter_modules: if empty/None → no filter applied.
    """
    if not os.path.isfile(MODULES_FILE):
        _die(
            f".config/modules.yaml not found.\n"
            f"Run './avm.sh setup --domains all' first."
        )

    modules: list[dict] = []
    cur: dict = {}

    with open(MODULES_FILE, encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip("\r\n")
            # skip comments and blank lines
            stripped = line.lstrip()
            if not stripped or stripped.startswith("#"):
                continue

            if "- name:" in line:
                if cur.get("name") and cur.get("url"):
                    _maybe_add(modules, cur, filter_domains, filter_types, filter_modules)
                cur = {"name": _field(line, "name"), "branch": "main",
                       "domain": "", "type": "", "url": ""}
            elif cur and "domain:" in line and "name:" not in line:
                cur["domain"] = _field(line, "domain")
            elif cur and "type:" in line:
                cur["type"] = _field(line, "type")
            elif cur and "url:" in line:
                cur["url"] = _field(line, "url")
            elif cur and "branch:" in line:
                cur["branch"] = _field(line, "branch")

    if cur.get("name") and cur.get("url"):
        _maybe_add(modules, cur, filter_domains, filter_types, filter_modules)

    return modules


def _field(line: str, key: str) -> str:
    """Extract value after 'key:' from a YAML line."""
    idx = line.find(f"{key}:")
    if idx == -1:
        return ""
    return _strip(line[idx + len(key) + 1:])


def _maybe_add(
    modules: list[dict],
    cur: dict,
    filter_domains: list[str] | None,
    filter_types:   list[str] | None,
    filter_modules: list[str] | None,
) -> None:
    if filter_domains and cur.get("domain") not in filter_domains:
        return
    if filter_types and cur.get("type") not in filter_types:
        return
    if filter_modules and cur.get("name") not in filter_modules:
        return
    modules.append(dict(cur))


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------

def repo_dir(mod: dict) -> str:
    return os.path.join(REPO_ROOT, mod["name"])


def is_cloned(mod: dict) -> bool:
    return os.path.isdir(os.path.join(repo_dir(mod), ".git"))


def _git(mod: dict, args: list[str], check: bool = True) -> subprocess.CompletedProcess:
    """Run a git command in a module's repo directory."""
    return subprocess.run(
        ["git", "-C", repo_dir(mod)] + args,
        capture_output=True,
        text=True,
        check=check,
    )


def _git_clone(mod: dict, depth: int = 1) -> subprocess.CompletedProcess:
    """Clone a repo into the workspace root."""
    cmd = ["git", "clone"]
    if depth:
        cmd += ["--depth", str(depth)]
    cmd += ["--branch", mod["branch"], mod["url"], repo_dir(mod)]
    return subprocess.run(cmd, capture_output=True, text=True)


# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------

SEP = "─" * 60


def _label(mod: dict) -> str:
    return f"{mod['name']}  [{mod['type']}] ({mod['domain']})"


def _print_result(
    symbol: str,
    verb: str,
    mod: dict,
    note: str = "",
) -> None:
    note_str = f"  {dim(note)}" if note else ""
    print(f"  {symbol}  {verb:<8}  {_label(mod)}{note_str}")


def _summary(ok_n: int, skip_n: int, fail_n: int) -> None:
    print(SEP)
    parts = [f"ok: {ok_n}", f"skipped: {skip_n}"]
    if fail_n:
        parts.append(err(f"failed: {fail_n}"))
    print("Done — " + ", ".join(parts))


# ---------------------------------------------------------------------------
# Subcommand: clone
# ---------------------------------------------------------------------------

def cmd_clone(
    modules: list[dict],
    full: bool = False,
    git_name: str = "",
    git_email: str = "",
    dry_run: bool = False,
) -> int:
    depth = 0 if full else 1
    mode = "full history" if full else "shallow (--depth 1)"

    if not dry_run:
        git_name, git_email = _prompt_git_identity(git_name, git_email)

    print(f"\nAVM clone — {len(modules)} modules  [{mode}]")
    print(SEP)

    ok_n = skip_n = fail_n = 0

    for mod in modules:
        if is_cloned(mod):
            _print_result(dim("-"), "SKIP", mod, "already cloned")
            skip_n += 1
            # still apply identity config even on skip
            if not dry_run:
                if git_name:
                    _git(mod, ["config", "user.name", git_name], check=False)
                if git_email:
                    _git(mod, ["config", "user.email", git_email], check=False)
            continue

        if dry_run:
            _print_result(dim("~"), "CLONE", mod, "dry-run")
            ok_n += 1
            continue

        print(f"  ↓  CLONE    {_label(mod)}")
        result = _git_clone(mod, depth=depth)
        if result.returncode == 0:
            if git_name:
                _git(mod, ["config", "user.name", git_name], check=False)
            if git_email:
                _git(mod, ["config", "user.email", git_email], check=False)
            ok_n += 1
        else:
            stderr = result.stderr.strip().splitlines()
            note = stderr[-1] if stderr else "clone failed"
            _print_result(err("✗"), "FAIL", mod, note)
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


# ---------------------------------------------------------------------------
# Subcommand: update (pull --ff-only)
# ---------------------------------------------------------------------------

def _do_update(mod: dict, dry_run: bool) -> tuple[str, str, str]:
    """Returns (status, label, note) — runs in a thread."""
    label = _label(mod)
    if not is_cloned(mod):
        return ("skip", label, "not cloned")
    if dry_run:
        return ("dry", label, "")
    result = _git(mod, ["pull", "--ff-only", "--quiet"], check=False)
    if result.returncode == 0:
        return ("ok", label, "")
    note = (result.stderr or result.stdout).strip().splitlines()
    return ("fail", label, note[-1] if note else "pull failed")


def cmd_update(
    modules: list[dict],
    parallel: int = 1,
    dry_run: bool = False,
) -> int:
    cloneable = modules
    print(f"\nAVM update — {len(cloneable)} modules  [parallel: {parallel}]")
    print(SEP)

    ok_n = skip_n = fail_n = 0
    results = _run_parallel(_do_update, cloneable, parallel, dry_run)

    for status, label, note in results:
        if status == "ok":
            print(f"  {ok('✓')}  PULL     {label}")
            ok_n += 1
        elif status == "skip":
            print(f"  {dim('-')}  SKIP     {label}  {dim(note)}")
            skip_n += 1
        elif status == "dry":
            print(f"  {dim('~')}  PULL     {label}  {dim('dry-run')}")
            ok_n += 1
        else:
            print(f"  {err('✗')}  FAIL     {label}  {dim(note)}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


# ---------------------------------------------------------------------------
# Subcommand: fetch
# ---------------------------------------------------------------------------

def _do_fetch(mod: dict, dry_run: bool) -> tuple[str, str, str]:
    label = _label(mod)
    if not is_cloned(mod):
        return ("skip", label, "not cloned")
    if dry_run:
        return ("dry", label, "")
    result = _git(mod, ["fetch", "--quiet", "--prune"], check=False)
    if result.returncode == 0:
        return ("ok", label, "")
    note = (result.stderr or result.stdout).strip().splitlines()
    return ("fail", label, note[-1] if note else "fetch failed")


def cmd_fetch(
    modules: list[dict],
    parallel: int = 20,
    dry_run: bool = False,
) -> int:
    print(f"\nAVM fetch — {len(modules)} modules  [parallel: {parallel}]")
    print(SEP)

    ok_n = skip_n = fail_n = 0
    results = _run_parallel(_do_fetch, modules, parallel, dry_run)

    for status, label, note in results:
        if status == "ok":
            print(f"  {ok('✓')}  FETCH    {label}")
            ok_n += 1
        elif status == "skip":
            print(f"  {dim('-')}  SKIP     {label}  {dim(note)}")
            skip_n += 1
        elif status == "dry":
            print(f"  {dim('~')}  FETCH    {label}  {dim('dry-run')}")
            ok_n += 1
        else:
            print(f"  {err('✗')}  FAIL     {label}  {dim(note)}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


# ---------------------------------------------------------------------------
# Subcommand: status
# ---------------------------------------------------------------------------

def _get_staleness_days(mod: dict) -> int | None:
    """Read the module YAML and return the age in days of the oldest analysis block.

    Returns None if the YAML cannot be read or no analysis blocks are found.
    """
    mod_name = mod.get("name", "")
    mod_type = mod.get("type", "")
    # Derive slug: strip the "terraform-azurerm-" prefix
    slug = mod_name.removeprefix("terraform-azurerm-")
    if not slug or not mod_type:
        return None

    yaml_path = os.path.join(MODULES_DIR, mod_type, f"{slug}.yaml")
    try:
        with open(yaml_path, encoding="utf-8", errors="replace") as f:
            content = f.read()
    except OSError:
        return None

    now = datetime.now(timezone.utc)
    oldest_days: int | None = None

    for m in re.finditer(r'^\s+checked_at:\s+"([^"]+)"', content, re.MULTILINE):
        try:
            ts  = datetime.fromisoformat(m.group(1).replace("Z", "+00:00"))
            age = max(0, (now - ts).days)
            if oldest_days is None or age > oldest_days:
                oldest_days = age
        except ValueError:
            pass

    return oldest_days


def _do_status(mod: dict, _dry_run: bool) -> tuple[str, str, str]:
    """
    Returns (status, label, note).
    status: 'clean' | 'dirty' | 'behind' | 'skip' | 'fail'
    """
    label = _label(mod)
    if not is_cloned(mod):
        return ("skip", label, "not cloned")

    # Check for uncommitted changes
    st = _git(mod, ["status", "--porcelain"], check=False)
    if st.returncode != 0:
        return ("fail", label, "git status failed")
    dirty = bool(st.stdout.strip())

    # Check how far behind/ahead of upstream
    ahead_behind = _git(
        mod,
        ["rev-list", "--count", "--left-right", "@{u}...HEAD"],
        check=False,
    )
    behind = ahead = 0
    if ahead_behind.returncode == 0 and ahead_behind.stdout.strip():
        parts = ahead_behind.stdout.strip().split()
        if len(parts) == 2:
            behind, ahead = int(parts[0]), int(parts[1])

    if dirty:
        note = f"dirty{f', {behind}↓ {ahead}↑' if behind or ahead else ''}"
        return ("dirty", label, note)
    if behind or ahead:
        return ("behind", label, f"{behind}↓ {ahead}↑")
    return ("clean", label, "")


def cmd_status(
    modules:            list[dict],
    parallel:           int = 20,
    dry_run:            bool = False,
    stale_threshold:    int = _DEFAULT_STALE_THRESHOLD,
) -> int:
    print(f"\nAVM status — {len(modules)} modules  (stale threshold: {stale_threshold}d)")
    print(SEP)

    results = _run_parallel(_do_status, modules, parallel, dry_run)

    clean_n = dirty_n = behind_n = skip_n = fail_n = stale_n = 0
    for (status, label, note), mod in zip(results, modules):
        # Compute staleness annotation
        stale_days = _get_staleness_days(mod)
        if stale_days is not None and stale_days >= stale_threshold:
            stale_sfx = warn(f" [stale {stale_days}d]")
            stale_n += 1
        else:
            stale_sfx = ""

        if status == "clean":
            if stale_sfx:
                print(f"  {ok('✓')}  CLEAN    {label}{stale_sfx}")
            clean_n += 1
        elif status == "dirty":
            print(f"  {warn('!')}  DIRTY    {label}  {warn(note)}{stale_sfx}")
            dirty_n += 1
        elif status == "behind":
            print(f"  {warn('↓')}  BEHIND   {label}  {warn(note)}{stale_sfx}")
            behind_n += 1
        elif status == "skip":
            print(f"  {dim('-')}  SKIP     {label}  {dim(note)}")
            skip_n += 1
        else:
            print(f"  {err('✗')}  FAIL     {label}  {err(note)}{stale_sfx}")
            fail_n += 1

    print(SEP)
    print(
        f"Clean: {clean_n}  |  Dirty: {dirty_n}  |  "
        f"Behind/ahead: {behind_n}  |  Not cloned: {skip_n}"
        + (f"  |  Stale analysis: {warn(str(stale_n))}" if stale_n else "")
    )
    return 0


# ---------------------------------------------------------------------------
# Subcommand: branch
# ---------------------------------------------------------------------------

def cmd_branch_create(
    modules: list[dict],
    name: str,
    dry_run: bool = False,
) -> int:
    print(f"\nAVM branch create '{name}' — {len(modules)} modules")
    print(SEP)

    ok_n = skip_n = fail_n = 0
    for mod in modules:
        label = _label(mod)
        if not is_cloned(mod):
            print(f"  {dim('-')}  SKIP     {label}  {dim('not cloned')}")
            skip_n += 1
            continue

        # Check if branch already exists
        check = _git(mod, ["rev-parse", "--verify", name], check=False)
        if check.returncode == 0:
            print(f"  {dim('-')}  EXISTS   {label}  {dim(f'branch {name!r} already exists')}")
            skip_n += 1
            continue

        if dry_run:
            print(f"  {dim('~')}  CREATE   {label}  {dim('dry-run')}")
            ok_n += 1
            continue

        result = _git(mod, ["checkout", "-b", name], check=False)
        if result.returncode == 0:
            print(f"  {ok('✓')}  CREATE   {label}")
            ok_n += 1
        else:
            note = (result.stderr or result.stdout).strip().splitlines()
            print(f"  {err('✗')}  FAIL     {label}  {err(note[-1] if note else 'failed')}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


def cmd_branch_checkout(
    modules: list[dict],
    name: str,
    fallback: bool = False,
    dry_run: bool = False,
) -> int:
    """
    Switch to branch `name`. If the branch doesn't exist:
    - with --fallback: stay on default branch (warn, don't fail)
    - without --fallback: warn and count as failed
    """
    print(f"\nAVM branch checkout '{name}' — {len(modules)} modules")
    print(SEP)

    ok_n = skip_n = fail_n = 0
    for mod in modules:
        label = _label(mod)
        if not is_cloned(mod):
            print(f"  {dim('-')}  SKIP     {label}  {dim('not cloned')}")
            skip_n += 1
            continue

        if dry_run:
            print(f"  {dim('~')}  CHECKOUT {label}  {dim('dry-run')}")
            ok_n += 1
            continue

        result = _git(mod, ["checkout", name], check=False)
        if result.returncode == 0:
            print(f"  {ok('✓')}  CHECKOUT {label}")
            ok_n += 1
        elif fallback:
            print(f"  {warn('~')}  FALLBACK {label}  {warn(f'branch {name!r} not found, staying on current')}")
            skip_n += 1
        else:
            note = (result.stderr or result.stdout).strip().splitlines()
            print(f"  {err('✗')}  FAIL     {label}  {err(note[-1] if note else 'checkout failed')}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


def cmd_branch_delete(
    modules: list[dict],
    name: str,
    force: bool = False,
    dry_run: bool = False,
) -> int:
    flag = "-D" if force else "-d"
    print(f"\nAVM branch delete '{name}' ({flag}) — {len(modules)} modules")
    print(SEP)

    ok_n = skip_n = fail_n = 0
    for mod in modules:
        label = _label(mod)
        if not is_cloned(mod):
            print(f"  {dim('-')}  SKIP     {label}  {dim('not cloned')}")
            skip_n += 1
            continue

        # Check if branch exists
        check = _git(mod, ["rev-parse", "--verify", name], check=False)
        if check.returncode != 0:
            print(f"  {dim('-')}  SKIP     {label}  {dim(f'branch {name!r} not found')}")
            skip_n += 1
            continue

        if dry_run:
            print(f"  {dim('~')}  DELETE   {label}  {dim('dry-run')}")
            ok_n += 1
            continue

        result = _git(mod, ["branch", flag, name], check=False)
        if result.returncode == 0:
            print(f"  {ok('✓')}  DELETE   {label}")
            ok_n += 1
        else:
            note = (result.stderr or result.stdout).strip().splitlines()
            print(f"  {err('✗')}  FAIL     {label}  {err(note[-1] if note else 'delete failed')}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


# ---------------------------------------------------------------------------
# Subcommand: stash / stash pop
# ---------------------------------------------------------------------------

def _cmd_stash_op(
    modules: list[dict],
    op: str,
    dry_run: bool = False,
) -> int:
    """op is 'push' (stash) or 'pop'."""
    verb = "STASH" if op == "push" else "STASH POP"
    print(f"\nAVM {verb.lower()} — {len(modules)} modules")
    print(SEP)

    ok_n = skip_n = fail_n = 0
    for mod in modules:
        label = _label(mod)
        if not is_cloned(mod):
            print(f"  {dim('-')}  SKIP     {label}  {dim('not cloned')}")
            skip_n += 1
            continue
        if dry_run:
            print(f"  {dim('~')}  {verb:<8} {label}  {dim('dry-run')}")
            ok_n += 1
            continue

        git_args = ["stash", op] if op == "pop" else ["stash"]
        result = _git(mod, git_args, check=False)
        if result.returncode == 0:
            note = result.stdout.strip().splitlines()
            print(f"  {ok('✓')}  {verb:<8} {label}  {dim(note[0] if note else '')}")
            ok_n += 1
        else:
            note = (result.stderr or result.stdout).strip().splitlines()
            print(f"  {err('✗')}  FAIL     {label}  {err(note[-1] if note else 'stash failed')}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


def cmd_stash(modules: list[dict], dry_run: bool = False) -> int:
    return _cmd_stash_op(modules, "push", dry_run)


def cmd_stash_pop(modules: list[dict], dry_run: bool = False) -> int:
    return _cmd_stash_op(modules, "pop", dry_run)


# ---------------------------------------------------------------------------
# Subcommand: reset
# ---------------------------------------------------------------------------

def cmd_reset(
    modules: list[dict],
    hard: bool = False,
    dry_run: bool = False,
) -> int:
    flag = "--hard" if hard else "--mixed"
    print(f"\nAVM reset ({flag} HEAD) — {len(modules)} modules")
    print(SEP)

    ok_n = skip_n = fail_n = 0
    for mod in modules:
        label = _label(mod)
        if not is_cloned(mod):
            print(f"  {dim('-')}  SKIP     {label}  {dim('not cloned')}")
            skip_n += 1
            continue
        if dry_run:
            print(f"  {dim('~')}  RESET    {label}  {dim('dry-run')}")
            ok_n += 1
            continue

        result = _git(mod, ["reset", flag, "HEAD"], check=False)
        if result.returncode == 0:
            print(f"  {ok('✓')}  RESET    {label}")
            ok_n += 1
        else:
            note = (result.stderr or result.stdout).strip().splitlines()
            print(f"  {err('✗')}  FAIL     {label}  {err(note[-1] if note else 'reset failed')}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


# ---------------------------------------------------------------------------
# Subcommand: run (arbitrary command)
# ---------------------------------------------------------------------------

def cmd_run(
    modules: list[dict],
    cmd_args: list[str],
    parallel: int = 1,
    dry_run: bool = False,
) -> int:
    if not cmd_args:
        _die("'run' requires a command, e.g.: manage_repos.py run git log --oneline -5")

    cmd_str = " ".join(cmd_args)
    print(f"\nAVM run '{cmd_str}' — {len(modules)} modules  [parallel: {parallel}]")
    print(SEP)

    ok_n = fail_n = skip_n = 0

    def _do_run(mod: dict, _dry: bool) -> tuple[str, str, str]:
        label = _label(mod)
        if not is_cloned(mod):
            return ("skip", label, "not cloned")
        if _dry:
            return ("dry", label, "")
        result = subprocess.run(
            cmd_args,
            cwd=repo_dir(mod),
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            out = result.stdout.strip()
            return ("ok", label, out)
        note = (result.stderr or result.stdout).strip().splitlines()
        return ("fail", label, note[-1] if note else "command failed")

    results = _run_parallel(_do_run, modules, parallel, dry_run)

    for status, label, note in results:
        if status == "ok":
            print(f"  {ok('✓')}  RUN      {label}")
            if note:
                for line in note.splitlines():
                    print(f"             {dim(line)}")
            ok_n += 1
        elif status in ("skip", "dry"):
            print(f"  {dim('-')}  SKIP     {label}  {dim(note or 'dry-run')}")
            skip_n += 1
        else:
            print(f"  {err('✗')}  FAIL     {label}  {err(note)}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


# ---------------------------------------------------------------------------
# Subcommand: cleanup
# ---------------------------------------------------------------------------

def _orphan_dirty_detail(path: str) -> str:
    """Return a human-readable dirty summary for an orphaned repo, or '' if clean."""
    parts: list[str] = []

    # Uncommitted changes
    try:
        r = subprocess.run(
            ["git", "-C", path, "status", "--porcelain"],
            capture_output=True, text=True, check=False,
        )
        n_files = len([l for l in r.stdout.splitlines() if l.strip()])
        if n_files:
            parts.append(f"{n_files} uncommitted")
    except OSError:
        pass

    # Stash entries
    try:
        r = subprocess.run(
            ["git", "-C", path, "stash", "list"],
            capture_output=True, text=True, check=False,
        )
        n_stash = len([l for l in r.stdout.splitlines() if l.strip()])
        if n_stash:
            parts.append(f"stash({n_stash})")
    except OSError:
        pass

    # Unpushed commits (only when upstream is configured)
    try:
        r = subprocess.run(
            ["git", "-C", path, "rev-list", "--count", "HEAD", "^@{u}"],
            capture_output=True, text=True, check=False,
        )
        if r.returncode == 0:
            ahead = int(r.stdout.strip() or "0")
            if ahead:
                parts.append(f"{ahead}↑ unpushed")
    except (OSError, ValueError):
        pass

    return ", ".join(parts)


def cmd_cleanup(
    configured_modules: list[dict],
    dry_run: bool = False,
    force: bool = False,
) -> int:
    """Remove cloned repos that are not present in .config/modules.yaml."""
    configured_names = {m["name"] for m in configured_modules}

    # Discover all cloned terraform-azurerm-avm-* directories on disk
    found: list[str] = []
    try:
        entries = os.scandir(REPO_ROOT)
    except OSError as e:
        print(f"ERROR: cannot scan {REPO_ROOT}: {e}", file=sys.stderr)
        return 1

    with entries:
        for entry in entries:
            if (
                entry.is_dir(follow_symlinks=False)
                and entry.name.startswith("terraform-azurerm-avm-")
                and os.path.isdir(os.path.join(entry.path, ".git"))
            ):
                found.append(entry.name)

    orphans = sorted(n for n in found if n not in configured_names)

    if not orphans:
        print("Nothing to clean up — all cloned repos are in .config/modules.yaml.")
        return 0

    mode_note = "(dry-run)" if dry_run else ("(forced)" if force else "")
    print(f"\nAVM cleanup — {len(orphans)} orphaned repo(s)  {mode_note}".rstrip())
    print(SEP)

    removed_n = skipped_n = 0

    for name in orphans:
        path = os.path.join(REPO_ROOT, name)
        dirty_detail = _orphan_dirty_detail(path)

        if dirty_detail and not force:
            print(f"  {warn('!')}  SKIP     {name}  {warn('dirty: ' + dirty_detail)}")
            skipped_n += 1
        elif dry_run:
            suffix = f"  {dim('dirty: ' + dirty_detail)}" if dirty_detail else ""
            print(f"  →  WOULD REMOVE  {name}{suffix}")
            removed_n += 1
        else:
            try:
                shutil.rmtree(path)
                suffix = f"  {dim('(was dirty: ' + dirty_detail + ')')}" if dirty_detail else ""
                print(f"  {ok('✓')}  REMOVE   {name}{suffix}")
                removed_n += 1
            except OSError as e:
                print(f"  {err('✗')}  FAIL     {name}  {err(str(e))}", file=sys.stderr)

    print(SEP)
    if dry_run:
        print(f"Dry run — would remove: {removed_n}  |  skipped (dirty): {skipped_n}")
    else:
        print(f"Removed: {removed_n}  |  Skipped (dirty): {skipped_n}")

    return 0


# ---------------------------------------------------------------------------
# Parallelism helper
# ---------------------------------------------------------------------------

def _run_parallel(
    fn,
    modules: list[dict],
    parallel: int,
    dry_run: bool,
) -> list[tuple[str, str, str]]:
    """
    Run fn(mod, dry_run) for each module in a thread pool.
    Returns results in the original module order.
    """
    parallel = max(1, parallel)
    if parallel == 1:
        return [fn(mod, dry_run) for mod in modules]

    results: list[tuple[str, str, str]] = [("", "", "")] * len(modules)
    with ThreadPoolExecutor(max_workers=parallel) as pool:
        future_to_idx = {pool.submit(fn, mod, dry_run): i for i, mod in enumerate(modules)}
        for future in as_completed(future_to_idx):
            idx = future_to_idx[future]
            try:
                results[idx] = future.result()
            except Exception as exc:  # noqa: BLE001
                results[idx] = ("fail", _label(modules[idx]), str(exc))
    return results


# ---------------------------------------------------------------------------
# CLI parsing
# ---------------------------------------------------------------------------

def _die(msg: str) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def _parse_filter(flag: str, value: str) -> list[str]:
    """Parse a filter flag value.

    'all'         → [] (no filter — match everything)
    'a,b,c'       → ['a', 'b', 'c']
    '' or ','     → error (empty value not allowed)
    'all,foo'     → error (cannot mix 'all' with specific values)
    """
    stripped = value.strip()
    if not stripped:
        _die(f"{flag} requires a non-empty value")
    if stripped.lower() == "all":
        return []
    parts = [p.strip() for p in stripped.split(",") if p.strip()]
    if not parts:
        _die(f"{flag}: invalid value '{value}' — use 'all' or a comma-separated list")
    if any(p.lower() == "all" for p in parts):
        _die(f"{flag}: cannot mix 'all' with specific values")
    return parts


def _print_usage() -> None:
    print("""
Usage: python3 scripts/manage_repos.py <subcommand> [options]

Subcommands:
  clone   [filters] [--full] [--git-name N] [--git-email E]
  update  [filters] [--parallel N]
  fetch   [filters] [--parallel N]
  status  [filters]
  branch create  <name> [filters] [--dry-run]
  branch checkout <name> [filters] [--fallback] [--dry-run]
  branch delete  <name> [filters] [--force] [--dry-run]
  stash   [filters] [--dry-run]
  stash pop [filters] [--dry-run]
  reset   [filters] [--hard] [--dry-run]
  run     <git-or-shell-cmd...> [filters] [--parallel N] [--dry-run]
  cleanup [--force] [--dry-run]

Filters (accepted by all subcommands):
  --domains <list|all>   Comma-separated domain slugs, or 'all' (e.g. networking,compute)
  --types <list|all>     Comma-separated types, or 'all' (res,ptn,utl)
  --modules <list|all>   Comma-separated module names, or 'all'
  --domain <slug>        Alias for --domains (single value)
  --type   <res|ptn|utl> Alias for --types (single value)
  --module <name>        Alias for --modules (single value, backward compat)

Global options:
  --dry-run              Print what would happen without executing
  -h, --help             Show this help
""")


class Args:
    """Simple parsed arguments container."""
    subcommand: str = ""
    sub2: str = ""
    branch_name: str = ""
    domains: list[str]
    types: list[str]
    modules: list[str]
    dry_run: bool = False
    full: bool = False
    git_name: str = ""
    git_email: str = ""
    parallel: int = 0
    fallback: bool = False
    force: bool = False
    hard: bool = False
    stale_threshold: int = _DEFAULT_STALE_THRESHOLD
    run_cmd: list[str] = []


def parse_args(argv: list[str]) -> Args:
    a = Args()
    a.domains = []
    a.types = []
    a.modules = []
    a.run_cmd = []
    it = iter(argv)

    def nextval(flag: str) -> str:
        try:
            return next(it)
        except StopIteration:
            _die(f"{flag} requires a value")
            return ""

    first = True
    for token in it:
        if first:
            first = False
            if token in ("-h", "--help", "help"):
                _print_usage()
                sys.exit(0)
            a.subcommand = token
            # branch and stash have a second positional token
            if token in ("branch", "stash"):
                sub2 = next(it, "")
                if not sub2:
                    _die(f"'{token}' requires a sub-operation (e.g. create/checkout/delete or pop)")
                a.sub2 = sub2
                # branch also needs a name
                if token == "branch":
                    name = next(it, "")
                    if not name or name.startswith("--"):
                        _die("'branch' requires a branch name after the operation")
                    a.branch_name = name
            continue

        if a.subcommand == "run" and not token.startswith("--"):
            # collect remaining non-flag tokens as the run command
            a.run_cmd.append(token)
            continue

        if token == "--domains":
            a.domains = _parse_filter("--domains", nextval("--domains"))
        elif token.startswith("--domains="):
            a.domains = _parse_filter("--domains", token.split("=", 1)[1])
        elif token == "--domain":
            # backward-compat alias: single value treated as a one-element list
            a.domains = [nextval("--domain")]
        elif token.startswith("--domain="):
            a.domains = [token.split("=", 1)[1]]
        elif token == "--types":
            a.types = _parse_filter("--types", nextval("--types"))
        elif token.startswith("--types="):
            a.types = _parse_filter("--types", token.split("=", 1)[1])
        elif token == "--type":
            # backward-compat alias: single value
            a.types = [nextval("--type")]
        elif token.startswith("--type="):
            a.types = [token.split("=", 1)[1]]
        elif token == "--modules":
            a.modules = _parse_filter("--modules", nextval("--modules"))
        elif token.startswith("--modules="):
            a.modules = _parse_filter("--modules", token.split("=", 1)[1])
        elif token == "--module":
            # backward-compat alias: single value
            a.modules = [nextval("--module")]
        elif token.startswith("--module="):
            a.modules = [token.split("=", 1)[1]]
        elif token == "--parallel":
            a.parallel = int(nextval("--parallel"))
        elif token.startswith("--parallel="):
            a.parallel = int(token.split("=", 1)[1])
        elif token == "--git-name":
            a.git_name = nextval("--git-name")
        elif token.startswith("--git-name="):
            a.git_name = token.split("=", 1)[1]
        elif token == "--git-email":
            a.git_email = nextval("--git-email")
        elif token.startswith("--git-email="):
            a.git_email = token.split("=", 1)[1]
        elif token == "--dry-run":
            a.dry_run = True
        elif token == "--full":
            a.full = True
        elif token == "--fallback":
            a.fallback = True
        elif token == "--force":
            a.force = True
        elif token == "--hard":
            a.hard = True
        elif token == "--stale-threshold":
            try:
                a.stale_threshold = int(nextval("--stale-threshold"))
            except (ValueError, SystemExit):
                _die("--stale-threshold requires an integer value")
        elif token.startswith("--stale-threshold="):
            try:
                a.stale_threshold = int(token.split("=", 1)[1])
            except ValueError:
                _die("--stale-threshold requires an integer value")
        elif token == "-h" or token == "--help":
            _print_usage()
            sys.exit(0)
        elif a.subcommand == "run":
            a.run_cmd.append(token)
        else:
            _die(f"Unknown option: {token}")

    return a


def _prompt_git_identity(git_name: str, git_email: str) -> tuple[str, str]:
    """Prompt for git user.name / user.email when not supplied via flags.

    Identity is always set explicitly in each repo's local config — global git
    config is intentionally ignored.  Press Enter to leave a field blank (no
    local config written for that field).  Skips the prompt when stdin is not a
    TTY (non-interactive run).
    """
    if not sys.stdin.isatty():
        return git_name, git_email

    needs_prompt = not git_name or not git_email
    if not needs_prompt:
        return git_name, git_email

    print()
    print("  Git identity (set explicitly in each repo — Enter to skip a field):")

    if not git_name:
        try:
            git_name = input("  user.name : ").strip()
        except EOFError:
            git_name = ""

    if not git_email:
        try:
            git_email = input("  user.email: ").strip()
        except EOFError:
            git_email = ""

    print()
    return git_name, git_email


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    if len(sys.argv) < 2:
        _print_usage()
        sys.exit(1)

    a = parse_args(sys.argv[1:])

    if not a.subcommand:
        _print_usage()
        sys.exit(1)

    if a.types:
        invalid = [t for t in a.types if t not in ALL_TYPES]
        if invalid:
            _die(f"--types: invalid value(s): {', '.join(invalid)}. Must be one of: {', '.join(ALL_TYPES)}")

    # cleanup compares against all configured modules — scope filters don't apply
    if a.subcommand == "cleanup":
        if a.domains or a.types or a.modules:
            print(
                "  NOTE: --domains/--types/--modules are ignored by cleanup "
                "(orphaned repos have no catalog metadata to filter on)."
            )
        all_modules = load_modules()
        sys.exit(cmd_cleanup(all_modules, dry_run=a.dry_run, force=a.force))

    modules = load_modules(filter_domains=a.domains, filter_types=a.types, filter_modules=a.modules)

    if not modules:
        msg = "No modules match the specified filters."
        if a.domains:
            msg += f"  --domains={','.join(a.domains)}"
        if a.types:
            msg += f"  --types={','.join(a.types)}"
        if a.modules:
            msg += f"  --modules={','.join(a.modules)}"
        print(msg)
        sys.exit(0)

    # Dispatch
    sub = a.subcommand
    rc = 0

    if sub == "clone":
        rc = cmd_clone(modules, full=a.full, git_name=a.git_name,
                       git_email=a.git_email, dry_run=a.dry_run)

    elif sub == "update":
        parallel = a.parallel or 1
        rc = cmd_update(modules, parallel=parallel, dry_run=a.dry_run)

    elif sub == "fetch":
        parallel = a.parallel or 20
        rc = cmd_fetch(modules, parallel=parallel, dry_run=a.dry_run)

    elif sub == "status":
        parallel = a.parallel or 20
        rc = cmd_status(modules, parallel=parallel, dry_run=a.dry_run,
                        stale_threshold=a.stale_threshold)

    elif sub == "branch":
        op = a.sub2
        if op == "create":
            rc = cmd_branch_create(modules, a.branch_name, dry_run=a.dry_run)
        elif op == "checkout":
            rc = cmd_branch_checkout(modules, a.branch_name,
                                     fallback=a.fallback, dry_run=a.dry_run)
        elif op == "delete":
            rc = cmd_branch_delete(modules, a.branch_name,
                                   force=a.force, dry_run=a.dry_run)
        else:
            _die(f"Unknown branch operation '{op}'. Use: create, checkout, delete")

    elif sub == "stash":
        if a.sub2 == "pop":
            rc = cmd_stash_pop(modules, dry_run=a.dry_run)
        else:
            rc = cmd_stash(modules, dry_run=a.dry_run)

    elif sub == "reset":
        rc = cmd_reset(modules, hard=a.hard, dry_run=a.dry_run)

    elif sub == "run":
        parallel = a.parallel or 1
        rc = cmd_run(modules, a.run_cmd, parallel=parallel, dry_run=a.dry_run)

    else:
        _die(f"Unknown subcommand '{sub}'. Run 'manage_repos.py help' for usage.")

    sys.exit(rc)


if __name__ == "__main__":
    main()
