#!/usr/bin/env python3
"""repos.py — Multi-repo git operations across AVM module workspace.

Reads .config/modules.yaml (generated by scripts/generate_config.py) and runs
git operations across all matched repos. Replaces clone_repos.sh/.ps1 and
update_repos.sh/.ps1 while adding fetch, status, branch management, stash,
reset, and arbitrary command pass-through.

Network-bound operations (fetch, update/pull) support parallel execution via
--parallel N to avoid waiting ~200-2000 ms per repo sequentially.

Usage:
    python3 scripts/repos.py clone   [filters] [--full] [--git-name N] [--git-email E]
    python3 scripts/repos.py update  [filters] [--parallel N]
    python3 scripts/repos.py fetch   [filters] [--parallel N]
    python3 scripts/repos.py status  [filters]
    python3 scripts/repos.py branch create <name>    [filters]
    python3 scripts/repos.py branch checkout <name>  [filters] [--fallback]
    python3 scripts/repos.py branch delete <name>    [filters] [--force]
    python3 scripts/repos.py stash   [filters]
    python3 scripts/repos.py stash pop [filters]
    python3 scripts/repos.py reset   [filters] [--hard]
    python3 scripts/repos.py run <cmd...> [-- filters]

Filters (accepted by all subcommands):
    --domain <name>        Filter by catalog domain slug (alias for --domains)
    --type <res|ptn|utl>   Filter by module type (alias for --types)
    --domains <list>       Comma-separated domain slugs (e.g. networking,compute)
    --types <list>         Comma-separated types (res,ptn,utl)
    --module <name>        Filter to a single module by name
    --dry-run              Print actions without executing

    ./avm.sh clone  →  python3 repos.py clone
    ./avm.sh update →  python3 repos.py update
"""

import os
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor, as_completed

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT    = os.path.dirname(SCRIPT_DIR)
MODULES_FILE = os.path.join(REPO_ROOT, ".config", "modules.yaml")

ALL_TYPES = ("res", "ptn", "utl")

# ---------------------------------------------------------------------------
# ANSI colours (no external libs)
# ---------------------------------------------------------------------------
_USE_COLOR = sys.stdout.isatty()


def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _USE_COLOR else text


def ok(s: str) -> str:   return _c("32", s)
def warn(s: str) -> str: return _c("33", s)
def err(s: str) -> str:  return _c("31", s)
def dim(s: str) -> str:  return _c("2", s)


# ---------------------------------------------------------------------------
# modules.yaml parser — line-by-line, stdlib only
# ---------------------------------------------------------------------------

def _strip(s: str) -> str:
    return s.strip().strip('"').strip("'")


def load_modules(
    filter_domains: list[str] | None = None,
    filter_types:   list[str] | None = None,
    filter_name:    str = "",
) -> list[dict]:
    """
    Parse .config/modules.yaml and return module dicts matching the given filters.

    Each dict has keys: name, domain, type, url, branch.
    filter_domains / filter_types: if empty/None → no filter applied.
    filter_name: if non-empty → match exact module name.
    """
    if not os.path.isfile(MODULES_FILE):
        _die(
            f".config/modules.yaml not found.\n"
            f"Run './avm.sh setup --domains all' first."
        )

    modules: list[dict] = []
    cur: dict = {}

    with open(MODULES_FILE, encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip("\r\n")
            # skip comments and blank lines
            stripped = line.lstrip()
            if not stripped or stripped.startswith("#"):
                continue

            if "- name:" in line:
                if cur.get("name") and cur.get("url"):
                    _maybe_add(modules, cur, filter_domains, filter_types, filter_name)
                cur = {"name": _field(line, "name"), "branch": "main",
                       "domain": "", "type": "", "url": ""}
            elif cur and "domain:" in line and "name:" not in line:
                cur["domain"] = _field(line, "domain")
            elif cur and "type:" in line:
                cur["type"] = _field(line, "type")
            elif cur and "url:" in line:
                cur["url"] = _field(line, "url")
            elif cur and "branch:" in line:
                cur["branch"] = _field(line, "branch")

    if cur.get("name") and cur.get("url"):
        _maybe_add(modules, cur, filter_domains, filter_types, filter_name)

    return modules


def _field(line: str, key: str) -> str:
    """Extract value after 'key:' from a YAML line."""
    idx = line.find(f"{key}:")
    if idx == -1:
        return ""
    return _strip(line[idx + len(key) + 1:])


def _maybe_add(
    modules: list[dict],
    cur: dict,
    filter_domains: list[str] | None,
    filter_types:   list[str] | None,
    filter_name:    str,
) -> None:
    if filter_domains and cur.get("domain") not in filter_domains:
        return
    if filter_types and cur.get("type") not in filter_types:
        return
    if filter_name and cur.get("name") != filter_name:
        return
    modules.append(dict(cur))


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------

def repo_dir(mod: dict) -> str:
    return os.path.join(REPO_ROOT, mod["name"])


def is_cloned(mod: dict) -> bool:
    return os.path.isdir(os.path.join(repo_dir(mod), ".git"))


def _git(mod: dict, args: list[str], check: bool = True) -> subprocess.CompletedProcess:
    """Run a git command in a module's repo directory."""
    return subprocess.run(
        ["git", "-C", repo_dir(mod)] + args,
        capture_output=True,
        text=True,
        check=check,
    )


def _git_clone(mod: dict, depth: int = 1) -> subprocess.CompletedProcess:
    """Clone a repo into the workspace root."""
    cmd = ["git", "clone"]
    if depth:
        cmd += ["--depth", str(depth)]
    cmd += ["--branch", mod["branch"], mod["url"], repo_dir(mod)]
    return subprocess.run(cmd, capture_output=True, text=True)


# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------

SEP = "─" * 60


def _label(mod: dict) -> str:
    return f"{mod['name']}  [{mod['type']}] ({mod['domain']})"


def _print_result(
    symbol: str,
    verb: str,
    mod: dict,
    note: str = "",
) -> None:
    note_str = f"  {dim(note)}" if note else ""
    print(f"  {symbol}  {verb:<8}  {_label(mod)}{note_str}")


def _summary(ok_n: int, skip_n: int, fail_n: int) -> None:
    print(SEP)
    parts = [f"ok: {ok_n}", f"skipped: {skip_n}"]
    if fail_n:
        parts.append(err(f"failed: {fail_n}"))
    print("Done — " + ", ".join(parts))


# ---------------------------------------------------------------------------
# Subcommand: clone
# ---------------------------------------------------------------------------

def cmd_clone(
    modules: list[dict],
    full: bool = False,
    git_name: str = "",
    git_email: str = "",
    dry_run: bool = False,
) -> int:
    depth = 0 if full else 1
    mode = "full history" if full else "shallow (--depth 1)"
    print(f"\nAVM clone — {len(modules)} modules  [{mode}]")
    print(SEP)

    ok_n = skip_n = fail_n = 0

    for mod in modules:
        if is_cloned(mod):
            _print_result(dim("-"), "SKIP", mod, "already cloned")
            skip_n += 1
            # still apply identity config even on skip
            if not dry_run:
                if git_name:
                    _git(mod, ["config", "user.name", git_name], check=False)
                if git_email:
                    _git(mod, ["config", "user.email", git_email], check=False)
            continue

        if dry_run:
            _print_result(dim("~"), "CLONE", mod, "dry-run")
            ok_n += 1
            continue

        print(f"  ↓  CLONE    {_label(mod)}")
        result = _git_clone(mod, depth=depth)
        if result.returncode == 0:
            if git_name:
                _git(mod, ["config", "user.name", git_name], check=False)
            if git_email:
                _git(mod, ["config", "user.email", git_email], check=False)
            ok_n += 1
        else:
            stderr = result.stderr.strip().splitlines()
            note = stderr[-1] if stderr else "clone failed"
            _print_result(err("✗"), "FAIL", mod, note)
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


# ---------------------------------------------------------------------------
# Subcommand: update (pull --ff-only)
# ---------------------------------------------------------------------------

def _do_update(mod: dict, dry_run: bool) -> tuple[str, str, str]:
    """Returns (status, label, note) — runs in a thread."""
    label = _label(mod)
    if not is_cloned(mod):
        return ("skip", label, "not cloned")
    if dry_run:
        return ("dry", label, "")
    result = _git(mod, ["pull", "--ff-only", "--quiet"], check=False)
    if result.returncode == 0:
        return ("ok", label, "")
    note = (result.stderr or result.stdout).strip().splitlines()
    return ("fail", label, note[-1] if note else "pull failed")


def cmd_update(
    modules: list[dict],
    parallel: int = 1,
    dry_run: bool = False,
) -> int:
    cloneable = modules
    print(f"\nAVM update — {len(cloneable)} modules  [parallel: {parallel}]")
    print(SEP)

    ok_n = skip_n = fail_n = 0
    results = _run_parallel(_do_update, cloneable, parallel, dry_run)

    for status, label, note in results:
        if status == "ok":
            print(f"  {ok('✓')}  PULL     {label}")
            ok_n += 1
        elif status == "skip":
            print(f"  {dim('-')}  SKIP     {label}  {dim(note)}")
            skip_n += 1
        elif status == "dry":
            print(f"  {dim('~')}  PULL     {label}  {dim('dry-run')}")
            ok_n += 1
        else:
            print(f"  {err('✗')}  FAIL     {label}  {dim(note)}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


# ---------------------------------------------------------------------------
# Subcommand: fetch
# ---------------------------------------------------------------------------

def _do_fetch(mod: dict, dry_run: bool) -> tuple[str, str, str]:
    label = _label(mod)
    if not is_cloned(mod):
        return ("skip", label, "not cloned")
    if dry_run:
        return ("dry", label, "")
    result = _git(mod, ["fetch", "--quiet", "--prune"], check=False)
    if result.returncode == 0:
        return ("ok", label, "")
    note = (result.stderr or result.stdout).strip().splitlines()
    return ("fail", label, note[-1] if note else "fetch failed")


def cmd_fetch(
    modules: list[dict],
    parallel: int = 20,
    dry_run: bool = False,
) -> int:
    print(f"\nAVM fetch — {len(modules)} modules  [parallel: {parallel}]")
    print(SEP)

    ok_n = skip_n = fail_n = 0
    results = _run_parallel(_do_fetch, modules, parallel, dry_run)

    for status, label, note in results:
        if status == "ok":
            print(f"  {ok('✓')}  FETCH    {label}")
            ok_n += 1
        elif status == "skip":
            print(f"  {dim('-')}  SKIP     {label}  {dim(note)}")
            skip_n += 1
        elif status == "dry":
            print(f"  {dim('~')}  FETCH    {label}  {dim('dry-run')}")
            ok_n += 1
        else:
            print(f"  {err('✗')}  FAIL     {label}  {dim(note)}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


# ---------------------------------------------------------------------------
# Subcommand: status
# ---------------------------------------------------------------------------

def _do_status(mod: dict, _dry_run: bool) -> tuple[str, str, str]:
    """
    Returns (status, label, note).
    status: 'clean' | 'dirty' | 'behind' | 'skip' | 'fail'
    """
    label = _label(mod)
    if not is_cloned(mod):
        return ("skip", label, "not cloned")

    # Check for uncommitted changes
    st = _git(mod, ["status", "--porcelain"], check=False)
    if st.returncode != 0:
        return ("fail", label, "git status failed")
    dirty = bool(st.stdout.strip())

    # Check how far behind/ahead of upstream
    ahead_behind = _git(
        mod,
        ["rev-list", "--count", "--left-right", "@{u}...HEAD"],
        check=False,
    )
    behind = ahead = 0
    if ahead_behind.returncode == 0 and ahead_behind.stdout.strip():
        parts = ahead_behind.stdout.strip().split()
        if len(parts) == 2:
            behind, ahead = int(parts[0]), int(parts[1])

    if dirty:
        note = f"dirty{f', {behind}↓ {ahead}↑' if behind or ahead else ''}"
        return ("dirty", label, note)
    if behind or ahead:
        return ("behind", label, f"{behind}↓ {ahead}↑")
    return ("clean", label, "")


def cmd_status(modules: list[dict], parallel: int = 20, dry_run: bool = False) -> int:
    print(f"\nAVM status — {len(modules)} modules")
    print(SEP)

    results = _run_parallel(_do_status, modules, parallel, dry_run)

    clean_n = dirty_n = behind_n = skip_n = fail_n = 0
    for status, label, note in results:
        if status == "clean":
            # only print non-clean unless -v
            clean_n += 1
        elif status == "dirty":
            print(f"  {warn('!')}  DIRTY    {label}  {warn(note)}")
            dirty_n += 1
        elif status == "behind":
            print(f"  {warn('↓')}  BEHIND   {label}  {warn(note)}")
            behind_n += 1
        elif status == "skip":
            print(f"  {dim('-')}  SKIP     {label}  {dim(note)}")
            skip_n += 1
        else:
            print(f"  {err('✗')}  FAIL     {label}  {err(note)}")
            fail_n += 1

    print(SEP)
    print(
        f"Clean: {clean_n}  |  Dirty: {dirty_n}  |  "
        f"Behind/ahead: {behind_n}  |  Not cloned: {skip_n}"
    )
    return 0


# ---------------------------------------------------------------------------
# Subcommand: branch
# ---------------------------------------------------------------------------

def cmd_branch_create(
    modules: list[dict],
    name: str,
    dry_run: bool = False,
) -> int:
    print(f"\nAVM branch create '{name}' — {len(modules)} modules")
    print(SEP)

    ok_n = skip_n = fail_n = 0
    for mod in modules:
        label = _label(mod)
        if not is_cloned(mod):
            print(f"  {dim('-')}  SKIP     {label}  {dim('not cloned')}")
            skip_n += 1
            continue

        # Check if branch already exists
        check = _git(mod, ["rev-parse", "--verify", name], check=False)
        if check.returncode == 0:
            print(f"  {dim('-')}  EXISTS   {label}  {dim(f'branch {name!r} already exists')}")
            skip_n += 1
            continue

        if dry_run:
            print(f"  {dim('~')}  CREATE   {label}  {dim('dry-run')}")
            ok_n += 1
            continue

        result = _git(mod, ["checkout", "-b", name], check=False)
        if result.returncode == 0:
            print(f"  {ok('✓')}  CREATE   {label}")
            ok_n += 1
        else:
            note = (result.stderr or result.stdout).strip().splitlines()
            print(f"  {err('✗')}  FAIL     {label}  {err(note[-1] if note else 'failed')}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


def cmd_branch_checkout(
    modules: list[dict],
    name: str,
    fallback: bool = False,
    dry_run: bool = False,
) -> int:
    """
    Switch to branch `name`. If the branch doesn't exist:
    - with --fallback: stay on default branch (warn, don't fail)
    - without --fallback: warn and count as failed
    """
    print(f"\nAVM branch checkout '{name}' — {len(modules)} modules")
    print(SEP)

    ok_n = skip_n = fail_n = 0
    for mod in modules:
        label = _label(mod)
        if not is_cloned(mod):
            print(f"  {dim('-')}  SKIP     {label}  {dim('not cloned')}")
            skip_n += 1
            continue

        if dry_run:
            print(f"  {dim('~')}  CHECKOUT {label}  {dim('dry-run')}")
            ok_n += 1
            continue

        result = _git(mod, ["checkout", name], check=False)
        if result.returncode == 0:
            print(f"  {ok('✓')}  CHECKOUT {label}")
            ok_n += 1
        elif fallback:
            print(f"  {warn('~')}  FALLBACK {label}  {warn(f'branch {name!r} not found, staying on current')}")
            skip_n += 1
        else:
            note = (result.stderr or result.stdout).strip().splitlines()
            print(f"  {err('✗')}  FAIL     {label}  {err(note[-1] if note else 'checkout failed')}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


def cmd_branch_delete(
    modules: list[dict],
    name: str,
    force: bool = False,
    dry_run: bool = False,
) -> int:
    flag = "-D" if force else "-d"
    print(f"\nAVM branch delete '{name}' ({flag}) — {len(modules)} modules")
    print(SEP)

    ok_n = skip_n = fail_n = 0
    for mod in modules:
        label = _label(mod)
        if not is_cloned(mod):
            print(f"  {dim('-')}  SKIP     {label}  {dim('not cloned')}")
            skip_n += 1
            continue

        # Check if branch exists
        check = _git(mod, ["rev-parse", "--verify", name], check=False)
        if check.returncode != 0:
            print(f"  {dim('-')}  SKIP     {label}  {dim(f'branch {name!r} not found')}")
            skip_n += 1
            continue

        if dry_run:
            print(f"  {dim('~')}  DELETE   {label}  {dim('dry-run')}")
            ok_n += 1
            continue

        result = _git(mod, ["branch", flag, name], check=False)
        if result.returncode == 0:
            print(f"  {ok('✓')}  DELETE   {label}")
            ok_n += 1
        else:
            note = (result.stderr or result.stdout).strip().splitlines()
            print(f"  {err('✗')}  FAIL     {label}  {err(note[-1] if note else 'delete failed')}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


# ---------------------------------------------------------------------------
# Subcommand: stash / stash pop
# ---------------------------------------------------------------------------

def _cmd_stash_op(
    modules: list[dict],
    op: str,
    dry_run: bool = False,
) -> int:
    """op is 'push' (stash) or 'pop'."""
    verb = "STASH" if op == "push" else "STASH POP"
    print(f"\nAVM {verb.lower()} — {len(modules)} modules")
    print(SEP)

    ok_n = skip_n = fail_n = 0
    for mod in modules:
        label = _label(mod)
        if not is_cloned(mod):
            print(f"  {dim('-')}  SKIP     {label}  {dim('not cloned')}")
            skip_n += 1
            continue
        if dry_run:
            print(f"  {dim('~')}  {verb:<8} {label}  {dim('dry-run')}")
            ok_n += 1
            continue

        git_args = ["stash", op] if op == "pop" else ["stash"]
        result = _git(mod, git_args, check=False)
        if result.returncode == 0:
            note = result.stdout.strip().splitlines()
            print(f"  {ok('✓')}  {verb:<8} {label}  {dim(note[0] if note else '')}")
            ok_n += 1
        else:
            note = (result.stderr or result.stdout).strip().splitlines()
            print(f"  {err('✗')}  FAIL     {label}  {err(note[-1] if note else 'stash failed')}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


def cmd_stash(modules: list[dict], dry_run: bool = False) -> int:
    return _cmd_stash_op(modules, "push", dry_run)


def cmd_stash_pop(modules: list[dict], dry_run: bool = False) -> int:
    return _cmd_stash_op(modules, "pop", dry_run)


# ---------------------------------------------------------------------------
# Subcommand: reset
# ---------------------------------------------------------------------------

def cmd_reset(
    modules: list[dict],
    hard: bool = False,
    dry_run: bool = False,
) -> int:
    flag = "--hard" if hard else "--mixed"
    print(f"\nAVM reset ({flag} HEAD) — {len(modules)} modules")
    print(SEP)

    ok_n = skip_n = fail_n = 0
    for mod in modules:
        label = _label(mod)
        if not is_cloned(mod):
            print(f"  {dim('-')}  SKIP     {label}  {dim('not cloned')}")
            skip_n += 1
            continue
        if dry_run:
            print(f"  {dim('~')}  RESET    {label}  {dim('dry-run')}")
            ok_n += 1
            continue

        result = _git(mod, ["reset", flag, "HEAD"], check=False)
        if result.returncode == 0:
            print(f"  {ok('✓')}  RESET    {label}")
            ok_n += 1
        else:
            note = (result.stderr or result.stdout).strip().splitlines()
            print(f"  {err('✗')}  FAIL     {label}  {err(note[-1] if note else 'reset failed')}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


# ---------------------------------------------------------------------------
# Subcommand: run (arbitrary command)
# ---------------------------------------------------------------------------

def cmd_run(
    modules: list[dict],
    cmd_args: list[str],
    parallel: int = 1,
    dry_run: bool = False,
) -> int:
    if not cmd_args:
        _die("'run' requires a command, e.g.: repos.py run git log --oneline -5")

    cmd_str = " ".join(cmd_args)
    print(f"\nAVM run '{cmd_str}' — {len(modules)} modules  [parallel: {parallel}]")
    print(SEP)

    ok_n = fail_n = skip_n = 0

    def _do_run(mod: dict, _dry: bool) -> tuple[str, str, str]:
        label = _label(mod)
        if not is_cloned(mod):
            return ("skip", label, "not cloned")
        if _dry:
            return ("dry", label, "")
        result = subprocess.run(
            cmd_args,
            cwd=repo_dir(mod),
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            out = result.stdout.strip()
            return ("ok", label, out)
        note = (result.stderr or result.stdout).strip().splitlines()
        return ("fail", label, note[-1] if note else "command failed")

    results = _run_parallel(_do_run, modules, parallel, dry_run)

    for status, label, note in results:
        if status == "ok":
            print(f"  {ok('✓')}  RUN      {label}")
            if note:
                for line in note.splitlines():
                    print(f"             {dim(line)}")
            ok_n += 1
        elif status in ("skip", "dry"):
            print(f"  {dim('-')}  SKIP     {label}  {dim(note or 'dry-run')}")
            skip_n += 1
        else:
            print(f"  {err('✗')}  FAIL     {label}  {err(note)}")
            fail_n += 1

    _summary(ok_n, skip_n, fail_n)
    return 1 if fail_n else 0


# ---------------------------------------------------------------------------
# Parallelism helper
# ---------------------------------------------------------------------------

def _run_parallel(
    fn,
    modules: list[dict],
    parallel: int,
    dry_run: bool,
) -> list[tuple[str, str, str]]:
    """
    Run fn(mod, dry_run) for each module in a thread pool.
    Returns results in the original module order.
    """
    parallel = max(1, parallel)
    if parallel == 1:
        return [fn(mod, dry_run) for mod in modules]

    results: list[tuple[str, str, str]] = [("", "", "")] * len(modules)
    with ThreadPoolExecutor(max_workers=parallel) as pool:
        future_to_idx = {pool.submit(fn, mod, dry_run): i for i, mod in enumerate(modules)}
        for future in as_completed(future_to_idx):
            idx = future_to_idx[future]
            try:
                results[idx] = future.result()
            except Exception as exc:  # noqa: BLE001
                results[idx] = ("fail", _label(modules[idx]), str(exc))
    return results


# ---------------------------------------------------------------------------
# CLI parsing
# ---------------------------------------------------------------------------

def _die(msg: str) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def _print_usage() -> None:
    print("""
Usage: python3 scripts/repos.py <subcommand> [options]

Subcommands:
  clone   [filters] [--full] [--git-name N] [--git-email E]
  update  [filters] [--parallel N]
  fetch   [filters] [--parallel N]
  status  [filters]
  branch create  <name> [filters] [--dry-run]
  branch checkout <name> [filters] [--fallback] [--dry-run]
  branch delete  <name> [filters] [--force] [--dry-run]
  stash   [filters] [--dry-run]
  stash pop [filters] [--dry-run]
  reset   [filters] [--hard] [--dry-run]
  run     <git-or-shell-cmd...> [filters] [--parallel N] [--dry-run]

Filters (accepted by all subcommands):
  --domains <list>       Comma-separated domain slugs (e.g. networking,compute)
  --types <list>         Comma-separated types (res,ptn,utl)
  --module <name>        Single module by name (e.g. avm-res-network-virtualnetwork)
  --domain <slug>        Alias for --domains (single value)
  --type   <res|ptn|utl> Alias for --types (single value)

Global options:
  --dry-run              Print what would happen without executing
  -h, --help             Show this help
""")


class Args:
    """Simple parsed arguments container."""
    subcommand: str = ""
    sub2: str = ""
    branch_name: str = ""
    domains: list[str]
    types: list[str]
    module: str = ""
    dry_run: bool = False
    full: bool = False
    git_name: str = ""
    git_email: str = ""
    parallel: int = 0
    fallback: bool = False
    force: bool = False
    hard: bool = False
    run_cmd: list[str] = []


def parse_args(argv: list[str]) -> Args:
    a = Args()
    a.domains = []
    a.types = []
    a.run_cmd = []
    it = iter(argv)

    def nextval(flag: str) -> str:
        try:
            return next(it)
        except StopIteration:
            _die(f"{flag} requires a value")

    first = True
    for token in it:
        if first:
            first = False
            if token in ("-h", "--help", "help"):
                _print_usage()
                sys.exit(0)
            a.subcommand = token
            # branch and stash have a second positional token
            if token in ("branch", "stash"):
                sub2 = next(it, "")
                if not sub2:
                    _die(f"'{token}' requires a sub-operation (e.g. create/checkout/delete or pop)")
                a.sub2 = sub2
                # branch also needs a name
                if token == "branch":
                    name = next(it, "")
                    if not name or name.startswith("--"):
                        _die("'branch' requires a branch name after the operation")
                    a.branch_name = name
            continue

        if a.subcommand == "run" and not token.startswith("--"):
            # collect remaining non-flag tokens as the run command
            a.run_cmd.append(token)
            continue

        if token == "--domains":
            a.domains = [d.strip() for d in nextval("--domains").split(",") if d.strip()]
        elif token.startswith("--domains="):
            a.domains = [d.strip() for d in token.split("=", 1)[1].split(",") if d.strip()]
        elif token == "--domain":
            # backward-compat alias: single value treated as a one-element list
            a.domains = [nextval("--domain")]
        elif token.startswith("--domain="):
            a.domains = [token.split("=", 1)[1]]
        elif token == "--types":
            a.types = [t.strip() for t in nextval("--types").split(",") if t.strip()]
        elif token.startswith("--types="):
            a.types = [t.strip() for t in token.split("=", 1)[1].split(",") if t.strip()]
        elif token == "--type":
            # backward-compat alias: single value
            a.types = [nextval("--type")]
        elif token.startswith("--type="):
            a.types = [token.split("=", 1)[1]]
        elif token == "--module":
            a.module = nextval("--module")
        elif token.startswith("--module="):
            a.module = token.split("=", 1)[1]
        elif token == "--parallel":
            a.parallel = int(nextval("--parallel"))
        elif token.startswith("--parallel="):
            a.parallel = int(token.split("=", 1)[1])
        elif token == "--git-name":
            a.git_name = nextval("--git-name")
        elif token.startswith("--git-name="):
            a.git_name = token.split("=", 1)[1]
        elif token == "--git-email":
            a.git_email = nextval("--git-email")
        elif token.startswith("--git-email="):
            a.git_email = token.split("=", 1)[1]
        elif token == "--dry-run":
            a.dry_run = True
        elif token == "--full":
            a.full = True
        elif token == "--fallback":
            a.fallback = True
        elif token == "--force":
            a.force = True
        elif token == "--hard":
            a.hard = True
        elif token == "-h" or token == "--help":
            _print_usage()
            sys.exit(0)
        elif a.subcommand == "run":
            a.run_cmd.append(token)
        else:
            _die(f"Unknown option: {token}")

    return a


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    if len(sys.argv) < 2:
        _print_usage()
        sys.exit(1)

    a = parse_args(sys.argv[1:])

    if not a.subcommand:
        _print_usage()
        sys.exit(1)

    if a.types:
        invalid = [t for t in a.types if t not in ALL_TYPES]
        if invalid:
            _die(f"--types: invalid value(s): {', '.join(invalid)}. Must be one of: {', '.join(ALL_TYPES)}")

    modules = load_modules(filter_domains=a.domains, filter_types=a.types, filter_name=a.module)

    if not modules:
        msg = "No modules match the specified filters."
        if a.domains:
            msg += f"  --domains={','.join(a.domains)}"
        if a.types:
            msg += f"  --types={','.join(a.types)}"
        if a.module:
            msg += f"  --module={a.module}"
        print(msg)
        sys.exit(0)

    # Dispatch
    sub = a.subcommand
    rc = 0

    if sub == "clone":
        rc = cmd_clone(modules, full=a.full, git_name=a.git_name,
                       git_email=a.git_email, dry_run=a.dry_run)

    elif sub == "update":
        parallel = a.parallel or 1
        rc = cmd_update(modules, parallel=parallel, dry_run=a.dry_run)

    elif sub == "fetch":
        parallel = a.parallel or 20
        rc = cmd_fetch(modules, parallel=parallel, dry_run=a.dry_run)

    elif sub == "status":
        parallel = a.parallel or 20
        rc = cmd_status(modules, parallel=parallel, dry_run=a.dry_run)

    elif sub == "branch":
        op = a.sub2
        if op == "create":
            rc = cmd_branch_create(modules, a.branch_name, dry_run=a.dry_run)
        elif op == "checkout":
            rc = cmd_branch_checkout(modules, a.branch_name,
                                     fallback=a.fallback, dry_run=a.dry_run)
        elif op == "delete":
            rc = cmd_branch_delete(modules, a.branch_name,
                                   force=a.force, dry_run=a.dry_run)
        else:
            _die(f"Unknown branch operation '{op}'. Use: create, checkout, delete")

    elif sub == "stash":
        if a.sub2 == "pop":
            rc = cmd_stash_pop(modules, dry_run=a.dry_run)
        else:
            rc = cmd_stash(modules, dry_run=a.dry_run)

    elif sub == "reset":
        rc = cmd_reset(modules, hard=a.hard, dry_run=a.dry_run)

    elif sub == "run":
        parallel = a.parallel or 1
        rc = cmd_run(modules, a.run_cmd, parallel=parallel, dry_run=a.dry_run)

    else:
        _die(f"Unknown subcommand '{sub}'. Run 'repos.py help' for usage.")

    sys.exit(rc)


if __name__ == "__main__":
    main()
